### ISSUE TITLE
Python errors

### ISSUE THREAD

**Issue by rx-209** [torproject/onionbalance#2]
Greetings George.
Trying to run onionbalance, v3_dev_wip branch. Got errors:

Traceback (most recent call last):
  File "/usr/local/bin/onionbalance", line 11, in <module>
    load_entry_point('OnionBalance==0.1.8', 'console_scripts', 'onionbalance')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named onionbalance.hs_v2.manager

**Comment by asn-d6** [comment]
Hello. Thanks for the interest and the bug report!
This repo and branch are not yet usable.
Please check back in the future for the full thing or wait for a blog post (Q1 2020)!
