### ISSUE TITLE
Onionbalance gets killed with assert about the size of hash ring

### ISSUE THREAD

**Issue by gits7r** [torproject/onionbalance#20]
If backend instances do not set `HiddenServiceOnionbalanceInstance 1` in their torrc, onionbalance is killed:

Traceback (most recent call last):
  File "/usr/local/bin/onionbalance", line 11, in <module>
    load_entry_point('OnionBalance==0.1.9+14.g5864dfc', 'console_scripts', 'onionbalance')()
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/manager.py", line 31, in main
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/hs_v3/manager.py", line 40, in main
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/common/scheduler.py", line 87, in run_all
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/common/scheduler.py", line 79, in _run_job
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/common/scheduler.py", line 45, in run
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/hs_v3/onionbalance.py", line 162, in publish_all_descriptors
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/hs_v3/service.py", line 238, in publish_descriptors
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/hs_v3/service.py", line 306, in _publish_descriptor
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/hs_v3/hashring.py", line 216, in get_responsible_hsdirs
AssertionError

This should be addressed to:
- if ALL backend instances are buggy configured, warn heavily that we cannot publish descriptors for the frontend service, because the backend instances are not functioning properly.

- continue running but warn heavily if just one (or more, but not ALL) backend instances do not set their `HiddenServiceOnionbalanceInstance 1` torrc line. Otherwise, if one backend is compromised for example, it can make the frontend unavaialble (regardless the other backend instances are functioning properly) until someone notices and changes manually.

**Comment by asn-d6** [comment]
Hmm, I don't quite see how that assert could be caused by the backend instances not having `HiddenServiceOnionbalanceInstance` set.

Also there is no real way for OBv3 to know if the instances have `HiddenServiceOnionbalanceInstance` set except if it does some sort of self-test to the instances, which should not be in scope for this ticket...

WRT why that assert triggered do you have the following info log from right before the assert:
```
    logger.info("Initialized hash ring of size %d (blinded key: %s)",
                len(node_hash_ring), base64.b64encode(blinded_pubkey))
```

If not and you can reproduce it would also help to add:
`logger.warning("responsible hsdirs: %d", len(responsible_hsdirs))`
right before the assert in line 216 of `hashring.py`.

**Comment by gits7r** [comment]
You are right. I caught it two times in a row so I was pretty sure that this was the reason. However, it is not.

And to make it worse, I cannot reproduce easily. I am waiting for it to occur, but it does not. Even if you do not set `HiddenServiceOnionbalanceInstance 1` on all backend instances, onionbalance will just stay and not do anything with its descriptors magic but not trigger this assert.

What else could have caused this?

**Comment by gits7r** [comment]
Yeah, there is no doubt that `HiddenServiceOnionbalanceInstance 1` unset in backend instance(s) is not to blame here. I just cannot reproduce this - could this assertion error be triggered by a malformed response from the HSDir?

**Comment by asn-d6** [comment]
I'm actually not sure, but I added a critical log in case this ever happens again to get more info: ce016c4

**Comment by asn-d6** [comment]
I'm gonna close this as I haven't heard about this for a while. If someone encounters it again, please feel free to open it.
