### ISSUE TITLE
UI: small fixes for the behavior of onionbalance-config interactive tool (fixes entirely PR #17)

### ISSUE THREAD

**Issue by gits7r** [torproject/onionbalance#24]
Opening a ticket with all the tweaks we need to do in PR #17 (all UI related) so we can track changes in the new onionbalance release. When these are addresses PR #17 can be merged to master.

1. **Entering a path to a Tor v3 onion service private key does not work (from PR #17 )**:

Traceback (most recent call last):
File "/usr/local/bin/onionbalance-config", line 11, in
load_entry_point('OnionBalance==0.1.9+14.g5864dfc', 'console_scripts', 'onionbalance-config')()
File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/config_generator/config_generator.py", line 446, in main
File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/config_generator/config_generator.py", line 40, in init
File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/config_generator/config_generator.py", line 58, in gather_information
File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/config_generator/config_generator.py", line 143, in load_master_key
File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/config_generator/config_generator.py", line 167, in load_v3_master_key
NotImplementedError

2. **onionbalance-config should be able to interrupt cleanly, discard any temporary configuration file (in case it was not saved yet) so the user can start over in case of a typo (from PR #17 ). Currently at interrupt we get:**

Traceback (most recent call last):
File "/usr/local/bin/onionbalance-config", line 11, in
load_entry_point('OnionBalance==0.1.9+14.g5864dfc', 'console_scripts', 'onionbalance-config')()
File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/config_generator/config_generator.py", line 446, in main
File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/config_generator/config_generator.py", line 40, in init
File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/config_generator/config_generator.py", line 50, in gather_information
File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/config_generator/config_generator.py", line 99, in get_output_path
KeyboardInterrupt

3. **Do not require for the entire DIRECTORY where oninobalance-config will store the configuration file to be totally empty. From PR #17** 

If one wants to put the Tor migrated hs_ed25519_secret_key inside the same directory with the config file, something totally normal and clean for anyone, it does not work. It says:
`[ERROR]: The specified output directory 'config/' is not empty. Please delete any files and folders or specify another output directory.`

onionbalance-config should not care if the folder where the user wants to store the configuration file is totally empty. Maybe one wants to set it in /var/lib/tor. So, it should only care if it finds a config.yaml file in the path provided as config path, not just any file or directory already existing in that path. It should only say something like:
"Path already contains a config.yaml file. This is likely to be a configuration file. Please check and remove it in order to proceed"

**Comment by asn-d6** [comment]
OK that was not easy but I did most of it!

(1) was done with 7c9cfe7, and (3) was done with 0b6d5ea.

However doing (2) would require some thought (so that I don't accidentally remove useful files), and I considered it of less severity so I didn't get to it. Perhaps let's close this ticket and open a new one just for (2)? Or we can repurpose this ticket.

**Comment by gits7r** [comment]
I agree about (2). Let us leave it aside for the time being and maybe think of a cancellation method while in the middle of the wizard of `onionbalance-config` in a separate ticket little bit later.
