### ISSUE TITLE
v3: Config file filtering: go deeper into -instances elements before starting up

### ISSUE THREAD

**Issue by gits7r** [torproject/onionbalance#27]
Right now, if onionbalance is missing `- instances` from the config file, it will correctly exit:

[WARNING]: Initializing onionbalance (version: 0.1.9+14.g5864dfc)...
[ERROR]: Config file is bad. 'instances' is missing. Did you make it with onionbalance-config?

But in case we have `- instances` set, but no data under it (no address / name parameters) it won't exit with an "[ERROR] Config file is bad. No backend instances are set. Onionbalance needs at least 1". instead:

Traceback (most recent call last):
  File "/usr/local/bin/onionbalance", line 11, in <module>
    load_entry_point('OnionBalance==0.1.9+14.g5864dfc', 'console_scripts', 'onionbalance')()
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/manager.py", line 31, in main
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/hs_v3/manager.py", line 27, in main
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/hs_v3/onionbalance.py", line 42, in init_subsystems
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+14.g5864dfc-py3.7.egg/onionbalance/hs_v3/onionbalance.py", line 95, in load_config_file
TypeError: 'NoneType' object is not iterable

**Comment by asn-d6** [comment]
Should be fixed in 11749d0! Thanks!

**Comment by gits7r** [comment]
It's much better, but you set `address:` with no invalid v3 hostname, or string that does not end with .onion, in fact just enter:

 ` - address:`
and nothing more. It will return:
Traceback (most recent call last):
  File "/usr/local/bin/onionbalance", line 11, in <module>
    load_entry_point('OnionBalance==0.1.9+30.g0dabbd1', 'console_scripts', 'onionbalance')()
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+30.g0dabbd1-py3.7.egg/onionbalance/manager.py", line 31, in main
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+30.g0dabbd1-py3.7.egg/onionbalance/hs_v3/manager.py", line 27, in main
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+30.g0dabbd1-py3.7.egg/onionbalance/hs_v3/onionbalance.py", line 42, in init_subsystems
  File "/usr/local/lib/python3.7/dist-packages/OnionBalance-0.1.9+30.g0dabbd1-py3.7.egg/onionbalance/hs_v3/onionbalance.py", line 106, in load_config_file
  File "/usr/local/lib/python3.7/dist-packages/stem-1.8.0-py3.7.egg/stem/descriptor/hidden_service.py", line 1141, in identity_key_from_address
    if onion_address.endswith('.onion'):
AttributeError: 'NoneType' object has no attribute 'endswith'

While we would expect:
`[ERROR]: Config file is bad. No backend instances are set. Onionbalance needs at least 1.`
