### ISSUE TITLE
stem.InvalidArguments: GETINFO request contained unrecognized keywords

### ISSUE THREAD

**Issue by afshar-mohammad** [torproject/onionbalance#6]
I finished setting up backend instances and made `config.yaml` ready. Now when I run `python3 onionbalance.py -v info -p 9051` I get this error:

```
2020-02-07 23:26:39,675 [WARNING]: Initializing onionbalance (version: 0+untagged.189.g7a19118)...
2020-02-07 23:26:39,682 [INFO]: Loaded the config file '../onionbalance/config.yaml'.
Traceback (most recent call last):
  File "onionbalance.py", line 10, in <module>
    onionbalance.hs_v3.manager.main()
  File "../onionbalance/onionbalance/hs_v3/manager.py", line 35, in main
    my_onionbalance.init_subsystems(args)
  File "../onionbalance/onionbalance/hs_v3/onionbalance.py", line 44, in init_subsystems    self.consensus = ob_consensus.Consensus()
  File "../onionbalance/onionbalance/hs_v3/consensus.py", line 36, in __init__
    self.refresh()
  File "../onionbalance/onionbalance/hs_v3/consensus.py", line 42, in refresh
    md_consensus_str = my_onionbalance.controller.get_md_consensus().encode()
  File "../onionbalance/onionbalance/hs_v3/stem_controller.py", line 54, in get_md_consensus
    return self.controller.get_info("dir/status-vote/current/consensus-microdesc")
  File "../onionbalance/obenv/lib/python3.8/site-packages/stem/control.py", line 489, in wrapped
    return func(self, *args, **kwargs)
  File "../onionbalance/obenv/lib/python3.8/site-packages/stem/control.py", line 1209, in get_info
    stem.response.convert('GETINFO', response)
  File "../onionbalance/obenv/lib/python3.8/site-packages/stem/response/__init__.py", line 124, in convert
    message._parse_message(**kwargs)
  File "../onionbalance/obenv/lib/python3.8/site-packages/stem/response/getinfo.py", line 44, in _parse_message
    raise stem.InvalidArguments('552', 'GETINFO request contained unrecognized keywords: %s\n' % ', '.join(unrecognized_keywords), unrecognized_keywords)
stem.InvalidArguments: GETINFO request contained unrecognized keywords: dir/status-vote/current/consensus-microdesc
```

When I run the onionbalance I just installed with `setup.py` like `onionbalance -v info -p 9051` I get a different error:

```
2020-02-07 23:28:35,232 [INFO]: Loaded the config file '../onionbalance/config.yaml'.
Traceback (most recent call last):
  File "../onionbalance/obenv/bin/onionbalance", line 11, in <module>
    load_entry_point('OnionBalance==0+untagged.189.g7a19118', 'console_scripts', 'onionbalance')()
  File "../onionbalance/obenv/lib/python3.8/site-packages/OnionBalance-0+untagged.189.g7a19118-py3.8.egg/onionbalance/hs_v2/manager.py", line 56, in main
NameError: name 'tor_socket' is not defined
```

It looks like that the installed onionbalance is using hs_v2 not hs_v3.

**Comment by asn-d6** [comment]
With regards to the GETINFO error, are you sure you are running tor with my `ticket32709_044_02` branch as indicated in https://github.com/asn-d6/onionbalance/blob/master/docs/alpha-testing-v3.txt ?

**Comment by afshar-mohammad** [comment]
Yes, I compiled your Tor from the mentioned branch for my backend services. I followed the instruction and I get `[info] ob_option_parse(): OnionBalance: MasterOnionAddress ...` in my info log.

For the frontend service I don't use your Tor. I use the standard Tor 4.2.6 because according to what I understand fron the guide any Tor above 4.2 is OK for frontend. Do I have to use your Tor for frontend too?

**Comment by asn-d6** [comment]
Yikes you are totally right that the frontend Tor should also be very recent. I suggest you use the latest official master (or you can also use my branch that would work too). Thanks for pointing this out; I tried to fix the guide in https://github.com/asn-d6/onionbalance/commit/64edd8467855b02ab05a9ae9af37d0f5a69a8c37 .

With regards to the other issue you pointed out in setup.py I pushed https://github.com/asn-d6/onionbalance/commit/36e7b5cae20c8300640872b05d7f8a45da907c4b which should hopefully improve the installation script to a point where the installed onionbalance should work. If it still doesn't work, feel free to just run it directly from source tree, and let me know so that I can fix it further.

Thanks for the bug reports!

**Comment by afshar-mohammad** [comment]
Thank you. I set up the frontend with your Tor and now everything works as expected. I have a fully functional load-balanced hidden service running. :-D

**Comment by asn-d6** [comment]
Hey! Glad to hear!! Thanks for the testing.

PLease let me know if you have any comments on making the guide easier to follow, or if you encounter any bugs or errors from now on!
